version: "3.9"

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mame_log
      POSTGRES_USER: phper
      POSTGRES_PASSWORD: secret
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  php-apache:
    build:
      context: ./docker/php
    ports: 
      - 8080:80
    volumes:
      - ./src:/var/www/mame_log
      - ./docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - db